name: Deploy to GitHub Pages

on:
  push:
    # Trigger the workflow on pushes to the branch you want to deploy from.
    # This should be the branch where your source code (React/Vite files) resides.
    # For your case, it's 'feature/react-deploy-success' or 'main' if you merge.
    branches:
      - feature/react-deploy-success # IMPORTANT: Change this to your main branch (e.g., 'main') after testing.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checkout your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use Node.js version 20 (or higher, e.g., '22')

      - name: Install dependencies
        run: npm install # Install project dependencies

      - name: Build project
        run: npm run build # Run your Vite build command, which creates the 'dist' folder

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Action to deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub's auto-generated token for this repo
          publish_dir: ./dist # IMPORTANT: This tells the action to deploy the 'dist' folder
          # The branch to publish to. This is usually 'gh-pages' for user/org pages,
          # or a specific branch like 'main' if you configure it that way in Pages settings.
          # For project pages, 'gh-pages' is a common default.
          publish_branch: gh-pages # This will create/update a 'gh-pages' branch
